export const CHANGE_FILTER_STATE = "CHANGE_FILTER_STATE";
export const CHANGE_AMOUNT_FILTER_STATE = "CHANGE_AMOUNT_FILTER_STATE";
export const CHANGE_PLAN_FILTER_STATE = "CHANGE_PLAN_FILTER_STATE";
export const CHANGE_SUB_FILTER_STATE = "CHANGE_SUB_FILTER_STATE";
export const RESET_FILTERS = "RESET_FILTERS";

export const CHANGE_SEARCH_TERM = "CHANGE_SEARCH_TERM";
export const CHANGE_RESULTS_VISIBILITY = "CHANGE_RESULTS_VISIBILITY";
export const FETCH_RESULT = "FETCH_RESULT";
export const FETCH_RESULT_SUCCESS = "FETCH_RESULT_SUCCESS";
export const FETCH_RESULT_FAILURE = "FETCH_RESULT_FAILURE";
