export const CHANGE_FILTER_STATE = "CHANGE_FILTER_STATE";

export const FETCH_RESULTS = "FETCH_RESULTS";
export const FETCH_RESULTS_SUCCESS = "FETCH_RESULTS_SUCCESS";
export const FETCH_RESULTS_FAILURE = "FETCH_RESULTS_FAILURE";
